Fix aggregation for sliding windows in C++

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -65,6 +65,7 @@ all: $(INSTALLED) examples
 .PHONY: \
   clean distclean all dep doc examples \
   check unit-check examples-check cpp-check \
+  aggregator-simplest-check aggregator-sets-check \
   install uninstall reinstall
 
 %.cmi: %.mli
@@ -312,7 +313,7 @@ convert-check: src/dessserc
 examples/i32s.csv: Makefile
 	@seq 1 10 > $@
 
-aggregator-check: src/dessserc examples/i32s.csv
+aggregator-simplest-check: src/dessserc examples/i32s.csv
 	@echo Testing aggregator
 	@schema='i32'; \
 	 ok=yes; \
@@ -335,7 +336,32 @@ aggregator-check: src/dessserc examples/i32s.csv
 	 done ;\
 	 if test "$$ok" = yes; then echo SUCCESS; else echo FAILURE; exit 1; fi
 
-check: unit-check examples-check cpp-check dump-load-check convert-check
+aggregator-sets-check: src/dessserc examples/i32s.csv
+	@echo Testing aggregator with sets
+	@schema='i32'; \
+	 ok=yes; \
+	 for be in OCaml C++; do \
+	   f="$$(tempfile --prefix=dessser_aggregator_check_)" &&\
+	   src/dessserc aggregator \
+	     --input-enc csv --output-enc s-expr -o "$$f" \
+	     --language=$$be --schema="$$schema" \
+	     --init '(sliding-window "i32" (u8 3))' \
+	     --update '(fun 0 "i32{}" "i32" (insert (param 0 0) (param 0 1)))' \
+	     --finalize '(fun 0 "i32{}" (param 0 0))'; \
+	   out=$$($$f -i examples/i32s.csv); \
+	   exp='3 (8 9 10)'; \
+	   if test "$$out" = "$$exp"; then \
+	     rm -f "$$f"* ;\
+	   else \
+	     echo "$$f failed for backend $$be: Expected $$exp but got $$out!" ;\
+	     ok=no ;\
+	   fi ;\
+	 done ;\
+	 if test "$$ok" = yes; then echo SUCCESS; else echo FAILURE; exit 1; fi
+
+check: \
+  unit-check examples-check cpp-check dump-load-check convert-check \
+  aggregator-simplest-check aggregator-sets-check
 
 # Installation
 
